server:
  port: 1234
spring: 
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: pass@word1
  jpa:    show-sql: true
    hibernate: 
      ddl-auto: update   
    
    